swagger: "2.0"
info:
  description: "Provides a simple echo service"
  version: "1.0.0"
  title: "Echo Service"
host: "my-examples-1095.appspot.com"
basePath: "/"
tags:
- name: "echo"
  description: "Everything about your Pets"
schemes:
- "https"
paths:
  /:
    post:
      tags:
      - "echo"
      summary: "Echos the body back"
      description: ""
      operationId: "echoPost"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "The message body to echo"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Message"    
        405:
          description: "Invalid input"
#securityDefinitions:
#  petstore_auth:
#    type: "oauth2"
#    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#    flow: "implicit"
#    scopes:
#      write:pets: "modify pets in your account"
#      read:pets: "read your pets"
#  api_key:
#    type: "apiKey"
#    name: "api_key"
#    in: "header"
definitions:
  Message:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
        example: "This is a test message"